print()
print('Desafio: Crie um script Python que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas de acordo com o valor digitado.')
print()
print('====== Desafio 01 ======')
nome = input('Qual o seu nome? ')
print('Olá', nome,'! Prazer em te conhecer!' )
